Feature/improve class scanning epmdj 10603
Drill4J/test2code-plugin pull request #405
Opened 2023-07-20 08:58 UTC by epamrsa

2023-07-27 16:47 UTC, RomanDavlyatshin requested changes
Need to discuss possible changes

2023-07-27 16:47 UTC, RomanDavlyatshin commented on test2code-agent/src/main/kotlin/com/epam/drill/plugins/test2code/classloading/ClassLoadersScanner.kt
> +    private fun addClassLoaderWithParents(loaders: MutableSet<ClassLoader>, classloader: ClassLoader) = loaders.apply {
tbd - mutating param

2023-07-27 16:47 UTC, RomanDavlyatshin commented on test2code-agent/src/main/kotlin/com/epam/drill/plugins/test2code/classloading/ClassLoadersScanner.kt
> +    private fun normalizeURIs(uris: Set<URI>) = mutableSetOf<URI>().apply {
I suggest implementing unit test, as function seems to handle lots of scenarios

2023-07-27 16:47 UTC, RomanDavlyatshin commented on test2code-agent/src/main/kotlin/com/epam/drill/plugins/test2code/classloading/ClassPathScanner.kt
> +    private val scannedJarFiles = mutableSetOf<String>()
tbd - state and mutability

2023-07-27 16:47 UTC, RomanDavlyatshin commented on test2code-agent/src/main/kotlin/com/epam/drill/plugins/test2code/classloading/ClassLoadersScanner.kt
> +    fun scanClasses(additionalPaths: List<String>) = additionalPaths.run {
Can we pass `additionalPaths` to constructor, defaulting to emptyList?

2023-07-27 16:47 UTC, RomanDavlyatshin commented on test2code-agent/src/main/kotlin/com/epam/drill/plugins/test2code/classloading/ClassLoadersScanner.kt
> +    transfer: (Set<ClassSource>) -> Unit
tbd - transfer responsiblity

2023-07-28 16:28 UTC, epamrsa commented
Discussed on code review session.

2023-07-28 16:28 UTC, merged